# fly.toml app configuration file generated for server-boatbooking on 2023-12-07T17:50:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-boatbooking"
primary_region = "mad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
